# Use an official Node.js runtime as a base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json, package-lock.json, and tsconfig.json to the working directory
COPY package*.json tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY src ./src

# Build the TypeScript code
RUN npm run compile

# Expose the default port
EXPOSE 8080

# CMD instruction dynamically sets the port based on the adapter type
CMD ["sh", "-c", "npm run adapters -- --port $(if [ \"$ADAPTER_TYPE\" = \"http\" ]; then echo 8883; else echo 3000; fi)"]