# Use an official Node.js runtime as a base image
FROM node:21-alpine

# Set the working directory in the container
WORKDIR /app

# Install build dependencies
RUN apk --no-cache add \
    python3 \
    make \
    g++ \
    && ln -sf /usr/bin/python3 /usr/bin/python

# Copy package.json, package-lock.json, and tsconfig.json to the working directory
COPY package*.json tsconfig.json ./

# Install app dependencies
RUN npm install

# Install AWS CLI using the bundled installer
RUN apk --no-cache add \
    bash \
    jq \
  && wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" \
  && unzip awscliv2.zip \
  && sudo ./aws/install \
  && rm awscliv2.zip

# Copy the source code to the working directory
COPY findr/adapters ./findr/adapters

# Build the TypeScript code
RUN npm run compile

# Expose the default port
# EXPOSE 8080

# CMD instruction dynamically sets the port based on the adapter type
# CMD ["sh", "-c", "npm run adapters -- --port $(if [ \"$ADAPTER_TYPE\" = \"http\" ]; then echo 3000; else echo 8883; fi)"]
CMD ["node", "./dist/index.js"]