name: Docker-Push

on:
  push:
    branches:
      - 'john/oracle'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Info
        run: |
          node -v
          npm -v

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          server-url: ${{ secrets.HARBOR_REGISTRY }}

      - name: Build and push adapters to Harbor
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_adapters
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/findr:adapters
