name: Docker-Push

on:
  push:
    branches:
      - 'john/oracle-or'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Info
        run: |
          node -v
          npm -v

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push adapters
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_oracle
          push: true
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          tags: pravnreddy429/findr_oracle:v33
=======
          tags: pravnreddy429/findr_oracle:v2
>>>>>>> 7332422 (oracle v2)
=======
          tags: pravnreddy429/findr_oracle:v4
>>>>>>> 60182f5 (pass env from kubernetes to oracle)
=======
          tags: pravnreddy429/findr_oracle:v5
>>>>>>> 42ec609 (change port to 9000)
=======
          tags: pravnreddy429/findr_oracle:v6
>>>>>>> a7740d3 (add certificate content)
=======
          tags: pravnreddy429/findr_oracle:v8
>>>>>>> 7711941 (add orchestrator-client, add aws credentials)
=======
          tags: pravnreddy429/findr_oracle:v14
>>>>>>> e1b4652 (v3 adapter v14 oracle)
=======
          tags: pravnreddy429/findr_oracle:v16
>>>>>>> 9c40817 (v16 oracle add new http parameters)
